title: "Portfolio - Ariel Simulevski"
description: "My portfolio, personal website, and blog.""
email: "ariel@simulevski.at"
url: "https://simulevski.at"

# Index page profile picture
profile_pic: profile_image.jpg

# Social links
socials:
  - title: "LinkedIn"
    url: "https://www.linkedin.com/in/ariel-s-369814130/"
    icon: "devicon:linkedin"
  - title: "GitHub"
    url: "https://github.com/Azer0s"
    icon: "skill-icons:github-dark"

# Analytics
google_analytics: G-6SFVRN5WHY

# Syntax highlighting
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'syntax'

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
